[install]
state = enabled
is_configured = true

[ui]
is_visible = true
label = OSCD Lab

[launcher]
author = Open Source Cybersecurity Degree (Australia)
description = Indexes, inputs and parsing for the OSCD Splunk lab dataset.
version = 0.1.0
